---
  - name: create testing database
    shell: influx -execute 'CREATE DATABASE localtest'
  - name: create grafana api key
    uri:
      url: http://localhost:3000/api/auth/keys
      method: POST
      force_basic_auth: yes
      user: admin
      password: admin
      return_content: yes
      body: {"role":"Admin","name":"testdata_api_key36"}
      body_format: json
    register: response
  - set_fact: apikey="{{ ((response.content) | from_json).key }}"
  - name: show generated API key
    debug:
      msg: "{{ apikey }}"
  - name: create influxdb datasource
    uri:
      url: http://localhost:3000/api/datasources
      method: POST
      headers:
        Authorization: "Bearer {{ apikey }}"
      return_content: yes
      body: {"name":"local_timeseriesdb","type":"influxdb","url":"http://localhost:8086","access":"proxy","database":"localtest","basicAuth":false}
      body_format: json
  - name: create influxdb datasource
    uri:
      url: http://localhost:3000/api/dashboards/db
      method: POST
      headers:
        Authorization: "Bearer {{ apikey }}"
      return_content: yes
      body: "{{ lookup('file','dashboard-conf.json') }}"
      body_format: json
  - name: copy script to send CPU data to local influxdb
    copy:
      src: transmit_cpu.sh
      dest: /tmp
      mode: 0775
